# Generated by Django 3.1.6 on 2021-02-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='idesc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
