# Generated by Django 3.1.6 on 2021-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0002_auto_20210216_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='iimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
