# Generated by Django 3.1.6 on 2021-02-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstore', '0003_item_iimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='iimg',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='iprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
